"""Add personal data fields to User model

Revision ID: 1efb1e93b8c8
Revises: 077f89319e73
Create Date: 2026-05-17 17:12:53.871284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1efb1e93b8c8'
down_revision = '077f89319e73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('login', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('profile_completed', sa.Boolean(), nullable=True))
        batch_op.create_unique_constraint('uq_user_login', ['login'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_login', type_='unique')
        batch_op.drop_column('profile_completed')
        batch_op.drop_column('password_hash')
        batch_op.drop_column('login')
        batch_op.drop_column('email')
        batch_op.drop_column('phone')
        batch_op.drop_column('last_name')

    # ### end Alembic commands ###
